# Generated by Django 5.0.4 on 2024-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LuckMessage",
            fields=[
                ("msg_id", models.AutoField(primary_key=True, serialize=False)),
                ("luck_date", models.CharField(blank=True, max_length=8, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("attribute1", models.CharField(blank=True, max_length=50, null=True)),
                ("attribute2", models.CharField(blank=True, max_length=50, null=True)),
                ("luck_msg", models.TextField(blank=True, null=True)),
                ("gpt_id", models.IntegerField(null=True)),
            ],
        ),
    ]
