# Generated by Django 5.0.6 on 2024-06-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=255)),
                ("app_name", models.CharField(max_length=100)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("token", "app_name")},
            },
        ),
    ]
