# Generated by Django 5.0.6 on 2024-06-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kluck_notifications", "0002_rename_app_name_devicetoken_device_os_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetoken",
            name="update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
