# Generated by Django 5.0.6 on 2024-06-17 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kluck_notifications", "0003_devicetoken_update_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="devicetoken",
            unique_together=set(),
        ),
    ]
