# Generated by Django 5.0.6 on 2024-06-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kluck_notifications", "0004_alter_devicetoken_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devicetoken",
            old_name="update_time",
            new_name="update_date",
        ),
    ]
