# Generated by Django 5.0.6 on 2024-06-03 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_settings", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="kluck_Admin",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("cell_num", models.CharField(blank=True, max_length=11, unique=True)),
                (
                    "adms_id",
                    models.ForeignKey(
                        db_column="admins_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admin_settings.adminsetting",
                    ),
                ),
            ],
        ),
    ]
