# Generated by Django 5.0.6 on 2024-06-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kluck_admin",
            name="adms_id",
        ),
    ]
