# Generated by Django 5.0.4 on 2024-05-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
