# Generated by Django 5.0.4 on 2024-05-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0002_alter_admin_create_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="last_date",
            field=models.DateTimeField(null=True),
        ),
    ]
