# Generated by Django 5.0.4 on 2024-05-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0003_admin_last_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="admin_id",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="admin",
            name="cell_num",
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name="admin",
            name="email",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
