# Generated by Django 5.0.4 on 2024-05-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0004_alter_admin_admin_id_alter_admin_cell_num_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admin",
            old_name="user_pw",
            new_name="admin_pw",
        ),
    ]
