# Generated by Django 5.0.6 on 2024-05-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0005_rename_user_pw_admin_admin_pw"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admin",
            old_name="admin_pw",
            new_name="password",
        ),
        migrations.AddField(
            model_name="admin",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
