# Generated by Django 5.0.6 on 2024-05-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0007_remove_admin_admin_id_remove_admin_permission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="admin_id",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
