# Generated by Django 5.0.6 on 2024-05-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0008_admin_admin_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="admin",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
