# Generated by Django 5.0.6 on 2024-05-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0010_admin_groups_admin_is_active_admin_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="admin_user",
        ),
    ]
