# Generated by Django 5.0.4 on 2024-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminSetting",
            fields=[
                ("adms_id", models.AutoField(primary_key=True, serialize=False)),
                ("push_time", models.CharField(blank=True, max_length=4, null=True)),
                ("update_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
