# Generated by Django 5.0.6 on 2024-06-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminSetting",
            fields=[
                ("adms_id", models.AutoField(primary_key=True, serialize=False)),
                ("push_time", models.CharField(default="0800", max_length=4)),
                ("term_date", models.CharField(default="0030", max_length=4)),
                ("term_time", models.CharField(default="0110", max_length=4)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
