# Generated by Django 5.0.6 on 2024-06-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminsetting",
            name="term_date",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="adminsetting",
            name="term_time",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
