# Generated by Django 5.0.6 on 2024-06-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminsetting",
            name="push_time",
            field=models.CharField(default="0800", max_length=4),
        ),
        migrations.AlterField(
            model_name="adminsetting",
            name="term_date",
            field=models.CharField(default="0030", max_length=4),
        ),
        migrations.AlterField(
            model_name="adminsetting",
            name="term_time",
            field=models.CharField(default="0110", max_length=4),
        ),
        migrations.AlterField(
            model_name="adminsetting",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
