# Generated by Django 5.0.6 on 2024-06-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GptPrompt",
            fields=[
                ("gpt_id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "prompt_msg_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("prompt_msg", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=30, null=True)),
                ("create_date", models.CharField(blank=True, max_length=8, null=True)),
                ("last_date", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "admins_id",
                    models.ForeignKey(
                        db_column="admins_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admins.kluck_admin",
                    ),
                ),
            ],
        ),
    ]
