# Generated by Django 5.0.4 on 2024-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GptPrompt",
            fields=[
                ("gpt_id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "prompt_msg_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("prompt_msg", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=30, null=True)),
                ("create_date", models.CharField(blank=True, max_length=8, null=True)),
                ("last_date", models.CharField(blank=True, max_length=8, null=True)),
                ("admins_id", models.IntegerField(null=True)),
            ],
        ),
    ]
